services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: malak
      POSTGRES_PASSWORD: malak
      # where to save data
      PGDATA: /var/lib/postgresql/data 
      # db created automatically
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 1240:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080 # on web 
      - 1025:1025 # on local used in app-dev.yml
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
